# Generated by Django 2.2 on 2019-04-11 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teleturniej', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorrectAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teleturniej.Answers')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teleturniej.Question')),
            ],
        ),
    ]
