# Generated by Django 2.2 on 2019-04-11 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teleturniej', '0002_correctanswer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answers',
            old_name='answer_four',
            new_name='answer',
        ),
        migrations.RemoveField(
            model_name='answers',
            name='answer_one',
        ),
        migrations.RemoveField(
            model_name='answers',
            name='answer_three',
        ),
        migrations.RemoveField(
            model_name='answers',
            name='answer_two',
        ),
    ]
