# Generated by Django 2.2 on 2019-04-11 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teleturniej', '0003_auto_20190411_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='level',
            field=models.CharField(choices=[(1, 'pierwszy_poziom'), (2, 'drugi_poziom'), (3, 'trzeci_poziom'), (4, 'czwarty_poziom'), (5, 'piaty_poziom'), (6, 'szosty_poziom'), (7, 'siodmy_poziom'), (8, 'osmy_poziom'), (9, 'dziewiaty_poziom'), (10, 'dziesiaty_poziom'), (11, 'jedenasty_poziom'), (12, 'dwunasty_poziom')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
